---
- hosts: ansible
  tasks:
  - name: create docker image
    command: docker build -t regapp:latest .
    args:
     chdir: /opt/docker

  - name: create tags to push image onto docker hub
    command: docker tag regapp:latest kundpl/regapp:latest

  - name: push docker images
    command: docker push kundpl/regapp:latest

