apiVersion: v1
kind: Service
metadata:
  name: canadajunebatch
  labels:
    app: regapp
spec:
    selector:
      app: regapp
    ports:
      - port: 8080
        targetPort: 8080
    type: LoadBalancer
